# Generated by Django 3.2.16 on 2022-10-11 17:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_and_cell', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('start_at', models.DateTimeField(verbose_name='Start On')),
                ('end_at', models.DateTimeField(verbose_name='End On')),
                ('is_organised', models.BooleanField(default=False, verbose_name='Is Organised')),
                ('club_cell', models.ManyToManyField(related_name='clubs_cells', to='club_and_cell.ClubCell', verbose_name='Clubs and Cells')),
                ('invited_faculty', models.ManyToManyField(related_name='invited_faculties', to=settings.AUTH_USER_MODEL, verbose_name='Invited Faculties')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('report_file', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Report File')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, null=True, size=None, verbose_name='Images')),
                ('rating', models.JSONField(blank=True, null=True, verbose_name='Rating')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.event', verbose_name='Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.place', verbose_name='Place'),
        ),
    ]
